baseURL = 'https://saiful-azree.github.io/saifulazree.ai/'
languageCode = 'en-us'
title = 'SAIFUL AZREE'
theme = 'lightbi-hugo'

[Params]
selfHosted = true
mainSections = ["posts"]
dateFormat = "02 January 2006"
showRelatedPosts = true 
previewCardImagePlacement = "bottom"
tagSubtitle = "Here, youâ€™ll discover the latest notes that explore new insights, and unique perspectives on the world."
homepageLayout = "profile" #blog
profileShortbio = "I am a Graduate Engineer with hands-on experience in computer vision projects. Passionate about applying image processing and machine learning techniques."
profilePhoto = "img/profile/profile-1.jpg"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
