baseURL = 'https://saiful-azree.github.io/saifulazree.ai/'
languageCode = 'en-us'
title = 'SAIFUL AZREE'
theme = 'lightbi-hugo'

[Params]
footerCopyright = "Saiful Azree"
selfHosted = true
mainSections = ["posts"]
dateFormat = "02 January 2006"
showRelatedPosts = true 
previewCardImagePlacement = "bottom"
homepageLayout = "profile"
profileShortbio = "I'm a Graduate Engineer with hands-on experience in computer vision projects. Passionate about applying image processing and machine learning techniques to solve real world problems and continuously improving technical skills."
profilePhoto = "img/profile/profile-1.jpg"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/posts/"
    weight = 2

[[menu.main]]
    name = "Certificates"
    url = "/"
    weight = 3
