baseURL = 'https://saiful-azree.github.io/saifulazree.ai/'
languageCode = 'en-us'
title = 'SAIFUL AZREE'
theme = 'lightbi-hugo'

[Params]
selfHosted = true
mainSections = ["posts"]
dateFormat = "02 January 2006"
showRelatedPosts = true 
previewCardImagePlacement = "bottom"
homepageLayout = "profile"
profileShortbio = "I’m passionate about the web platform and love creating for the web. Here, you'll find a mix of long essays, quick notes, and personal reflections on what I’ve learned throughout my journey."
profilePhoto = "img/profile/home-profile-pic.jpg"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
