baseURL = 'https://saiful-azree.github.io/saifulazree.ai/'
languageCode = 'en-us'
title = 'SAIFUL AZREE'
theme = 'lightbi-hugo'

[Params]
selfHosted = true
mainSections = ["posts"]
dateFormat = "02 January 2006"
socialShare = true
rss = false
showRelatedPosts = true 
previewCardImagePlacement = "bottom"
homepageLayout = "profile"
profileShortbio = "I'm a Computer Engineering student with hands-on experience in computer vision projects. Passionate about applying image processing and machine learning techniques to solve real world problems and continuously improving technical skills."
profilePhoto = "img/profile/profile-1.jpg"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "//"
    weight = 2

[[menu.main]]
    name = "Projects"
    url = "/posts/"
    weight = 3

[[menu.main]]
    name = "Certifications"
    url = "/certificates/"
    weight = 4

[[menu.main]]
    name = "Projects"
    url = "/posts/"
    weight = 2
